lightblue:
  build: .
  command: /opt/jbossas7/bin/standalone.sh -b 0.0.0.0 -Djboss.bind.address.management=0.0.0.0
  ports:
   - "8080:8080"
   - "9999:9999"
  links:
      - mongodb:mongodb
mongodb:
  image: dockerfile/mongodb
  command: mongod --rest --httpinterface --smallfiles
  ports:
   - "28017:28017"
   - "27017:27017"
applications:
  image: lightblue/applications:latest
  command: /opt/jbossas7/bin/standalone.sh -b 0.0.0.0
  ports:
   - "8081:8080"
  links:
   - lightblue
